// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_GUI();
Q_GHS_KEEP_REFERENCE(qml_register_types_GUI)

class GUIPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    GUIPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_GUI;
        Q_UNUSED(registration)
    }
};



#include "GUIplugin_GUIPlugin.moc"
